# -*- coding: utf-8 -*-
"""lab_ds_toolkit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/aoguedao/gmu-casbbi-nrt/blob/main/labs/lab_ds_toolkit.ipynb

# Activity - Data Science Toolkit

1. Create a GitHub account in the following [link](https://github.com/join).
1. Create a GitHub repository named `gmu_casbbi_nrt`. You can do it directly here https://github.com/new.
1. Launch this file in Google Colab pressing the `Launch Botton` in the upper right corner and then select `Colab`.
1. Modify the next cell with your answers.
1. Run all the cells.
1. Save the notebook as `about_me.ipynb` in your local files.
1. Upload it to your GitHub repository you just created.
"""

name = "Emily L. Gerson"
i_am_from = "Plymouth, Massachusetts"
program = "Psychology PhD with a concentration in Cognitive and Behavioral Neuroscience"
about_me = "I work in autism research, and have recently begun to explore the intersection between autism and substance abuse"
fun_fact = "I've been playing the violin since I was 3 years old"
reason_apply = "I wanted to explore more complex methods of data analysis, and was especially inspired by the community-engaged research model"

print(
    f"""
    My name is {name}, I am from {i_am_from} and I am enrolled in the {program} program at GMU.

    {about_me}. And a fun fact about me is that {fun_fact}.

    I applied to the CASBBI's NRT program because {reason_apply}.
    """
)